### ISSUE TITLE
Better CLI error messages for beginners

### ISSUE THREAD

**Issue by Irratzo** [JuDFTteam/aiida-fleur#208] opened 2023-04-24 12:35 UTC
One beginner mistake is to mistake the AiiDA CLI `verdi` with the AiiDA-FLEUR CLI `aiida-fleur`. This can lead to a user mistakingly typing, for instance, `aiida-fleur code list`, instead of `verdi code list`. Though the [docs](https://aiida-fleur.readthedocs.io/en/latest/user_guide/cmd/cmd_index.html) should make it clear how to use this correctly, a more helpful error message might also steer the user into the right direction. Currently (latest `develop` as well as `support/aiida-2.X`, commits  1d60f20 and 351121a, resp.), the following exception is thrown in the upper example.

```
(aiida-kernel) wasmer@e6e90ab90851:~/Home/JupyterHub(master *%=)$ aiida-fleur code list
Traceback (most recent call last):
  File "/opt/aiida-core/aiida/cmdline/params/types/profile.py", line 43, in convert
    config = ctx.obj.config
AttributeError: 'NoneType' object has no attribute 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/aiida-kernel/bin/aiida-fleur", line 33, in <module>
    sys.exit(load_entry_point('aiida-fleur', 'console_scripts', 'aiida-fleur')())
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 2316, in process_value
    value = self.type_cast_value(ctx, value)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/core.py", line 2304, in type_cast_value
    return convert(value)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/click/types.py", line 82, in __call__
    return self.convert(value, param, ctx)
  File "/opt/aiida-core/aiida/cmdline/params/types/profile.py", line 45, in convert
    raise RuntimeError(
RuntimeError: The context does not contain a user defined object with the loaded AiiDA configuration. Is your click command setting `context_class` to :class:`aiida.cmdline.groups.verdi.VerdiContext`?
```

**Comment by janssenhenning** [comment] 2023-05-12 14:16
This is actually not the error message that should pop up when entering a non-existent command

It was instead caused by the aiida-fleur CLI being completely broken somewhere between AiiDA >= 2.1.0 and 2.3.0

Fixed in 9480008

**Closed by janssenhenning** 2023-05-12 14:16 UTC
